### ISSUE TITLE
Where is the GT in Virtual Object Relighting (VOR) dataset for Qualitative Evaluation？

### ISSUE THREAD

**Issue by jxl0131** [Wanggcong/StyleLight#7]
Hi!

I notice that you may use [Virtual Object Relighting (VOR) dataset](https://github.com/fnzhan/EMLight#virtual-object-insertion--rendering) to evaluation qualitatively because i found you ask some question about this in the issue of EMLight, and there are some crops in the './StyleLight/assets/wild2/' folders.

I am trying to make Qualitative Evaluation, too. But i could not found the ground truth panaroma picture in their Virtual Object Relighting (VOR) dataset. So i want to ask you that have you found GT panaroma in VOR dataset? If you GT panaroma were not included in VOR, can you share this GT panaromas with me?

Thanks for sharing you excelent work！

**Comment by Wanggcong** [comment]
> Hi!
> 
> I notice that you may use [Virtual Object Relighting (VOR) dataset](https://github.com/fnzhan/EMLight#virtual-object-insertion--rendering) to evaluation qualitatively because i found you ask some question about this in the issue of EMLight, and there are some crops in the './StyleLight/assets/wild2/' folders.
> 
> I am trying to make Qualitative Evaluation, too. But i could not found the ground truth panaroma picture in their Virtual Object Relighting (VOR) dataset. So i want to ask you that have you found GT panaroma in VOR dataset? If you GT panaroma were not included in VOR, can you share this GT panaromas with me?
> 
> Thanks for sharing you excelent work！

Hi @jxl0131, Thanks for your attention for our work. 

Thare are no GT panorama in VOR dataset [Virtual Object Relighting (VOR) dataset](https://github.com/fnzhan/EMLight#virtual-object-insertion--rendering) , as described in their [Google Drive](https://drive.google.com/drive/folders/1mI3ufHgZOmHeShoezk77Gr_GhdqCPGif). You may double-check these folders. 

Since this dataset focuses on Virtual Object Relighting, you can insert some objects into it using estimated environmental maps and conduct user study to compare other methods. I hope this may help you.

**Comment by Wanggcong** [comment]
Thank you for the question. I closed this issue since there is no further question. You might re-open it or open a new issue if any.
